inherit_gem:
  boxt_rubocop:
    - rails.yml
    - rspec.yml

require:
  - boxt_rubocop
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0

Style/FetchEnvVar:
  Exclude:
    - spec/dummy/config/**/*
