inherit_gem:
  boxt_rubocop:
    - rails.yml
    - rspec.yml

inherit_mode:
  merge:
    - Exclude

require:
  - boxt_rubocop
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - gemfiles/**/*

Style/FetchEnvVar:
  Exclude:
    - spec/dummy/config/**/*
