inherit_gem:
  boxt_ruby_style_guide:
    - default.yml
    - rails.yml
    - rspec.yml

require:
  - rubocop-rails
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude
    - NewCops
    - TargetRubyVersion

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
