inherit_gem:
  rubocop-zuno:
    - rails.yml
    - rspec.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-zuno

plugins:
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - gemfiles/**/*

Style/FetchEnvVar:
  Exclude:
    - spec/dummy/config/**/*
